services:
  fluidsynth:
    container_name: fluidsynth
    build: https://github.com/scottgarner/fluidsynth-docker.git
    devices:
      - "/dev/snd:/dev/snd"
    cap_add:
      - SYS_NICE
    ports:
      - 9800:9800
