services:
  fluidsynth:
    build: .
    image: scottmadethis/fluidsynth-docker
    container_name: fluidsynth
    network_mode: host
    restart: always
    devices:
      - "/dev/snd:/dev/snd"
    cap_add:
      - SYS_NICE
    ports:
      - 9800:9800
